### ISSUE TITLE
About the model performance

### ISSUE THREAD

**Issue by aichicaideyang** [XiongxiaoXu/Mambaformer-in-Time-Series#2]
I'm now trying to reproduce this model through this repository. However, when I use the script given like etth1.sh. The performance is so poor, did I make any mistake?

**Comment by aichicaideyang** [comment]
It seems that the SST code is not available yet?

**Comment by XiongxiaoXu** [comment]
Hi, SST code is uploaded now. The previous one is Mambaformer, which corrsponds the old (and short) version of SST paper.
