### ISSUE TITLE
How to reproduce the results in the paper?

### ISSUE THREAD

**Issue by Leopold2333** [XiongxiaoXu/Mambaformer-in-Time-Series#3]
Hi, the decoder-only architecture seems good and I'm trying to reproduce the experimental results in your paper. I have run the `electricity.sh` and the setup of the script is somewhat inconsistent with the experiments in the paper.

1. In the paper, the look back window is set to $L=2S=672$. But in `electricity.sh`, `label_len` and `seq_len` is set to 192.
2. There seems no patching modules in your implementations?

I try to set `d_layers=2,3,4` and the results are consistently poor. Is your public bash's settings ok? Or did I make some wrong parameter settings?

**Comment by Mikaelgogogo** [comment]
Hello, are you running it in an additional virtual machine Ubuntu? Or in WSL2? I want to implement it in Win11 system now, I don't know if it is feasible.

**Comment by Leopold2333** [comment]
> Hello, are you running it in an additional virtual machine Ubuntu? Or in WSL2? I want to implement it in Win11 system now, I don't know if it is feasible.

WSL2, if you do not want your PC directly using Linux.

**Comment by Mikaelgogogo** [comment]
Thank you!

**Comment by XiongxiaoXu** [comment]
Hi, SST code is uploaded now. The previous one is Mambaformer, which corrsponds the old (and short) version of SST paper.

SST: https://arxiv.org/abs/2404.14757v2
Mambaformer: https://arxiv.org/abs/2404.14757v1
